<?php
require_once __DIR__ . '/../includes/pdf.php';

function assert_equal($expected, $actual, string $message): void
{
    if ($expected != $actual) {
        fwrite(STDERR, "FAIL: $message\n  expected: " . var_export($expected, true) . "\n  actual:   " . var_export($actual, true) . "\n");
        exit(1);
    }
    echo "PASS: $message\n";
}

function assert_true($actual, string $message): void
{
    assert_equal(true, (bool) $actual, $message);
}

// pdf_escape_string: backslashes and parens must be escaped for PDF literal strings.
assert_equal('a \\(b\\) c', pdf_escape_string('a (b) c'), 'parens are escaped');
assert_equal('back\\\\slash', pdf_escape_string('back\\slash'), 'backslash is escaped');

// pdf_wrap_text: short text fits on one line.
$lines = pdf_wrap_text('short text', 500, 9);
assert_equal(1, count($lines), 'text well within the width stays on one line');

// pdf_wrap_text: long text wraps to multiple lines, using all the words.
$long = 'This is a long sentence that should definitely wrap across more than one line at a narrow width.';
$lines = pdf_wrap_text($long, 100, 9);
assert_true(count($lines) > 1, 'long text at a narrow width wraps to multiple lines');
assert_equal(
    preg_replace('/\s+/', ' ', $long),
    preg_replace('/\s+/', ' ', implode(' ', $lines)),
    'wrapping does not drop or duplicate words'
);

// pdf_wrap_text: explicit newlines start new lines even if short.
$lines = pdf_wrap_text("line one\nline two", 500, 9);
assert_equal(['line one', 'line two'], $lines, 'explicit newlines are honored as line breaks');

// pdf_wrap_text: a single word wider than the column still gets its own line
// instead of disappearing or throwing.
$lines = pdf_wrap_text('averyveryverylongwordthatdoesnotfit', 20, 9);
assert_equal(1, count($lines), 'an unbreakable long word still produces exactly one line');

// build_table_pdf: basic structural sanity on the generated bytes.
$columns = [
    ['label' => 'Date', 'width' => 80, 'wrap' => false],
    ['label' => 'Hours', 'width' => 60, 'wrap' => false],
    ['label' => 'Description', 'width' => 375, 'wrap' => true],
];

$pdf = build_table_pdf('Title', 'Subtitle', $columns, [['2025-01-01', '5.00', 'Test']], 'Total: 5.00');
assert_true(str_starts_with($pdf, '%PDF-1.4'), 'output starts with the PDF header');
assert_true(str_ends_with(rtrim($pdf), '%%EOF'), 'output ends with %%EOF');
assert_true(strpos($pdf, 'startxref') !== false, 'output includes a startxref marker');

// An empty row set must still produce a single valid page, not crash or
// produce zero pages.
$emptyPdf = build_table_pdf('Title', 'Subtitle', $columns, [], 'Total: 0.00');
assert_true(str_starts_with($emptyPdf, '%PDF-1.4'), 'empty entry list still produces a valid PDF header');
assert_equal(1, substr_count($emptyPdf, '/Type /Page '), 'empty entry list produces exactly one page');

// Enough rows to force a page break: confirm more than one page is emitted
// and each page reports the correct total.
$manyRows = [];
for ($i = 0; $i < 60; $i++) {
    $manyRows[] = ["2025-01-$i", '5.00', "Entry $i"];
}
$multiPagePdf = build_table_pdf('Title', 'Subtitle', $columns, $manyRows, 'Total: 300.00');
$pageCount = substr_count($multiPagePdf, '/Type /Page ');
assert_true($pageCount > 1, 'enough rows force more than one page');
assert_true(strpos($multiPagePdf, "Page 1 of {$pageCount}") !== false, 'first page reports the correct total page count');

echo "All tests passed.\n";
